version: '3'

services:
  pct:
    build: .
    devices:
      - /dev/isgx
    volumes:
      - ${RUST_SDK_ROOT}:/root/sgx
      - ${PCT_DIR}:/root/sgx/samplecode/PCT
      - ${PCT_DIR}/docker/script/init.sh:/root/sgx/init.sh
    tty: true
    env_file: ${PCT_DIR}/.env
    command: /root/sgx/init.sh
    working_dir: /root/sgx/samplecode/PCT
    ports:
      - "50010:8080"